### ISSUE TITLE
Move config options in index.html to settings.toml

### ISSUE THREAD

**Issue by xiruizhao** [librespeed/speedtest-go#19]
For example whether to turn on telemetry.

**Comment by maddie** [comment]
I'm not sure about this change for now, since the Go version is mostly a re-implementation of the PHP version. Changing this means the frontends won't be 100% compatible (changing the telemetry setting within the frontend doesn't work the same in Go version anymore with this change), which could be a surprise for users migrating to Go.

**Comment by maddie** [comment]
Telemetry can now be disabled in the backend with `database_type` set to `none`.
